# Generated by Django 2.2 on 2020-02-02 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200202_0901'),
        ('offre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='usedbookdemandeur',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='offreusedbookdemandeur', to='store.Usedbook'),
        ),
    ]
