# Generated by Django 2.2 on 2020-02-02 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offre', '0002_offre_usedbookdemandeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='usedbookdemandeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offreusedbookdemandeur', to='store.Usedbook'),
        ),
    ]
