# Generated by Django 2.2 on 2020-01-06 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_book', models.CharField(max_length=100)),
                ('num_page_book', models.IntegerField()),
                ('author_book', models.CharField(max_length=100)),
                ('isbn_book', models.CharField(max_length=100)),
                ('image_book', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('descript_book', models.TextField()),
                ('langague_book', models.CharField(choices=[('ENG', 'English'), ('ARB', 'Arabic'), ('FR', 'Frenche'), ('Oth', 'Other')], max_length=100)),
                ('type', models.CharField(choices=[('USED', 'usedbook'), ('NEW', 'newbook')], default='usedbook', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_genre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usedbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat_book', models.TextField(default='availabel')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('etat_actu_book', models.IntegerField(default='9')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.Book')),
                ('user_usedbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Newbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start_sell', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity_book', models.IntegerField()),
                ('price_book', models.IntegerField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('stars_book', models.IntegerField(default='5')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.Book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genre_book',
            field=models.ManyToManyField(help_text='Select a genre for this book', to='store.Genre'),
        ),
    ]
