# Generated by Django 2.2 on 2020-01-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='langague_book',
            field=models.CharField(choices=[('English', 'English'), ('Arabic', 'Arabic'), ('Frenche', 'Frenche'), ('Other', 'Other')], max_length=100),
        ),
    ]
