# Generated by Django 2.0.7 on 2020-02-24 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_auto_20200202_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wishlist_book', models.CharField(max_length=100)),
                ('wishlist_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('wishlist_note', models.CharField(max_length=200)),
                ('wishlist_emailme', models.BooleanField()),
                ('wishlist_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
