# Generated by Django 2.2 on 2020-02-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookorder',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='bookorders',
            field=models.ManyToManyField(to='order.Bookorder'),
        ),
    ]
