# Generated by Django 2.0.7 on 2020-02-10 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200208_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookorder',
            old_name='book',
            new_name='newbook',
        ),
    ]
