# Generated by Django 2.0.7 on 2020-02-11 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200210_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('region_adress', models.CharField(max_length=256)),
                ('town_adress', models.CharField(max_length=256)),
                ('city_adress', models.CharField(max_length=256)),
                ('street_adress', models.CharField(max_length=256)),
                ('postal_code', models.IntegerField()),
                ('phone_num', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('shipping_type', models.CharField(choices=[('NORMAL', 'normal'), ('FAST', 'fast')], default='normal', max_length=100)),
                ('paying_type', models.CharField(choices=[('CCP', 'ccp'), ('HAND', 'hand')], default='ccp', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='order_delete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_submit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
        ),
    ]
